config/routes.rb
Rails.application.routes.draw do
   root 'cocktails#index'

  resources :ingredients
  resources :cocktails do
   resources :doses, except: :delete
 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete 'doses/:id', to: 'doses#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  def show
    @dose = Dose.new
    @show_doses = Dose.where(cocktail_id: @cocktail)
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails
  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cocktails/1
  def update
    if @cocktail.update(cocktail_params)
      redirect_to @cocktail, notice: 'Cocktail was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cocktails/1
  def destroy
    @cocktail.destroy
    redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cocktail_params
      params.require(:cocktail).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:show, :edit, :update, :destroy]

  # GET /doses
  def index
    @doses = Dose.all
  end

  # GET /doses/1
  def show
  end

  # GET /doses/new
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])

  end

  # GET /doses/1/edit
  def edit
  end

  # POST /doses
  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])

    if @dose.save
      redirect_to @dose.cocktail, notice: 'Dose was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /doses/1
  def update
    if @dose.update(dose_params)
      redirect_to @dose, notice: 'Dose was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /doses/1
  def destroy
    @dose.destroy
    redirect_to cocktail_path, notice: 'Dose was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dose
      @dose = Dose.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def dose_params
      params.require(:dose).permit(:cocktail_id, :ingredient_id, :description)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to @ingredient, notice: 'Ingredient was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ingredients/1
  def update
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient, notice: 'Ingredient was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ingredients/1
  def destroy
    @ingredient.destroy
    redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= form_with(model: cocktail, local: true) do |form| %>
  <% if cocktail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
      <% cocktail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="btn btn-cam">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cocktail_name %>
  </div>

  <div class="btn btn-cam" >
    <%= form.submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<div class='body-img'>
  <div class='container'>
    <h1 class='text-center' id='index-title'>The Red Door</h1>
    <div class='container'>
      <div class='row'>
        <% @cocktails.each do |cocktail| %>
        <div class='col-xs-12 col-sm-4'>
          <div class='card'>
            <div class='card-description'>
              <h2><%= cocktail.name %></h2>
              <ul style="list-style: none;">
              <li class="list"><%= link_to 'Show', cocktail %></li>
              <li class="list"><%= link_to 'Edit', edit_cocktail_path(cocktail) %></li>
              <li class="list"><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class=text-center>
<h2>New Cocktail</h2>

<%= render 'form', cocktail: @cocktail %>

<div class="btn btn-treehouse"><%= link_to 'Back', cocktails_path %>
</div>
</div>

app/views/cocktails/show.html.erb
<div class=container>
<div class="col-xs-12 col-sm-8 col-sm-offset-2 text-center ">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>

<%= link_to 'Edit', edit_cocktail_path(@cocktail), class: "btn btn-info"%>
<%= link_to 'Back', cocktails_path %>
<%= link_to 'Add new ingredient', new_cocktail_dose_path(@cocktail) %>
</div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :ingredient %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doses/edit.html.erb
<h1>Editing Dose</h1>

<%= render 'form' %>

<%= link_to 'Show', @dose %> |
<%= link_to 'Back', cocktails_path(@cocktail) %>

app/views/doses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doses</h1>

<table>
  <thead>
    <tr>
      <th>Cocktail</th>
      <th>Ingredient</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doses.each do |dose| %>
      <tr>
        <td><%= dose.cocktail %></td>
        <td><%= dose.ingredient %></td>
        <td><%= dose.description %></td>
        <td><%= link_to 'Show', dose %></td>
        <td><%= link_to 'Edit', edit_dose_path(dose) %></td>
        <td><%= link_to 'Destroy', dose, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dose', new_dose_path %>

app/views/doses/new.html.erb
<h1>New Dose</h1>

<%= render 'form', dose: @dose %>

<%= link_to 'Back', cocktail_path(@cocktail) %>

app/views/doses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cocktail:</strong>
  <%= @dose.cocktail %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @dose.ingredient %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dose.description %>
</p>

<%= link_to 'Edit', edit_dose_path(@dose) %> |
<%= link_to 'Back', doses_path %>

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ingredient_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <tr><%= link_to 'Show', ingredient %></tr>
        <tr><%= link_to 'Edit', edit_ingredient_path(ingredient) %></tr>
        <tr><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></tr>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <a href="#"><%= link_to 'New Cocktail', new_cocktail_path, class: "btn-medium" %></a>


    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "avatar.jpeg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>